version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test_gem:
    docker:
      - image: cimg/ruby:3.0.3
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run RSpec
          command: bundle exec rspec

  test_examples:
    docker:
      - image: cimg/ruby:3.0.3
      - image: circleci/postgres:alpine
        name: postgres
        environment:
          POSTGRES_PASSWORD: temporal
      - image: temporalio/auto-setup@sha256:1cf8fba342ff6311cb2ade9a67df989b68613e7e3efdb8d259d3a4e6be7e099f
        name: temporal
        environment:
          - DB=postgresql
          - DB_PORT=5432
          - POSTGRES_USER=postgres
          - POSTGRES_PWD=temporal
          - POSTGRES_SEEDS=postgres
          - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml

    environment:
      - TEMPORAL_HOST=temporal

    steps:
      - checkout

      - run:
          name: Bundle Install
          command: cd examples && bundle install --path vendor/bundle

      - run:
          name: Register Namespace
          command: cd examples && bin/register_namespace ruby-samples

      - run:
          name: Wait for Namespace to settle
          command: sleep 15

      - run:
          name: Boot up worker
          command: cd examples && bin/worker
          background: true

      - run:
          name: Boot up crypt worker
          command: cd examples && bin/worker
          background: true
          environment:
            USE_ENCRYPTION: 1

      - run:
          name: Run RSpec
          command: cd examples && bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test_gem
      - test_examples
