version: '3.5'

services:
  temporal:
    image: temporalio/auto-setup:latest
    ports:
     - "7233:7233"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/temporal-ruby.yaml"
    volumes:
      - ./dynamic-config.yml:/etc/temporal/config/dynamicconfig/temporal-ruby.yaml
    depends_on:
      - cassandra

  temporal-web:
    image: temporalio/web:latest
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
    ports:
      - "8088:8088"
    depends_on:
      - temporal

  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
